- accounts.json
- contacts.json
- opportunities.json
First round of data as requested by Product.
> First update to Summit 2023 data for accounts, contacts, and opps

- room_blocks.json
> DMSMVR-689

- opportunities.json
- room_blocks.json
Final data updates for Summit. Added notes to Opportunities, added full room block information for wedding opp
> Summit data april21

- forms.json
Add `form_type_id` to demo form records
DMSMVR-2090
> DMSMVR-2090 - Add Form Type to Forms

- forms.json
- update forms data for required layout. Setting it to just an empty layout manager as default
DMSMVR-2028
> Update forms data for layout

- forms.json
Reverts simpleviewinc/apex-prepare-demo#13
> Revert "Update forms data for layout"

- accounts.json
> DMSMVR-2348: Remove `accounts.sleeping_rooms`

- contacts.json
- forms.json
* Phones should use core phone_type_id .
* Emails should use core email_type_id .
* Forms should use core form_type_id .
> Dropdown audit

- room_blocks.json
> DMSMVR-2376: Update room_types remove ROH

- accommodation_facilities.json
- dining_facilities.json
- meeting_facilities.json
Updates for new schema on accommodation/dining/meeting facilities from DMSMVR-2519
> DMSMVR-2519

- leisure_events.json
-- Add related event tags
-- Add related offers
-- Add doors_open value
-- Add purchase_tickets URL
-- Add premium_upgrade URL
-- Add post dates
DMSMVR-2373
> DMSMVR-2373: Add new demo data for leisure events

- meeting_rooms.json
- sports_facility_spaces.json
Quick update to persist "column" data
> Updating column value to count to persist data while editing

- leisure_events.json
Changed the times from AM/PM to 24 hour format.
> DMSMVR-2650: Add Time Field to Leisure Event Form and Date Rule Set Form

- forms.json
Ticket: [DMSMVR-2644](https://simpleviewtools.atlassian.net/browse/DMSMVR-2644)
Added new form for Partner signup
[DMSMVR-2644]: https://simpleviewtools.atlassian.net/browse/DMSMVR-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-2644 - Public portal user signup

- accounts.json
- files.json
Created apex-test folder and re-uploaded images to Cloudinary.
> Add images to apex-test folder

- listings.json
- Remove account_id from listings data
DMSMVR-3048
> Remove account_id from listings data

- leisure_events.json
- listings.json
- offers.json
Ticket: [DMSMVR-3032](https://simpleviewtools.atlassian.net/browse/DMSMVR-3032)
Includes `draft`, `awaiting approval` and `rework` records for LEO.
Each record has been modified from its parent in order to create a delta of changes when viewing the draft.
Run prepare demo pointing to this repo:
```
{
"user": "sv-jschwarz",
"branch": "DMSMVR-3032"
}
```
[DMSMVR-3032]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3032 - Add some draft records to the Prepare Demo script

- listings.json
Added some DTN data to some listings
> DMSMVR-369 Updated listings to add DTN data.

- email_comms.json
Demo data added to email comms
> Email comms data

- bulletins.json
Added products to the bulletins
> DMSMVR-3073: AddProductSystemDropdwonToBulletins

- email_comms.json
Ticket: [DMSMVR-3222](https://simpleviewtools.atlassian.net/browse/DMSMVR-3222)
- Added type to email_comm records
- Added email_comm records of type "Preview"
[DMSMVR-3222]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3222 - Add Preview functionality to Emails Form

- module_configurable_fields.json
Add `is_shown_in_portal: true` configurable fields
> DMSMVR-3245: Show in portal only config fields

- leisure_events.json
[DMSMVR-3474](https://simpleviewtools.atlassian.net/browse/DMSMVR-3474)
The events have been updated to be mostly 2025, with a few left in 2024. They are also now evenly spread throughout the year.
Run the prepare demo script with these settings to ensure it is working:
```
{
"user": "jswill88",
"branch": "DMSMVR-3474-events-seed"
}
```
[DMSMVR-3474]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3474: Leisure Event Seed Data - Dates update

- forms.json
Ticket: [DMSMVR-3518](https://simpleviewtools.atlassian.net/browse/DMSMVR-3518)
Form without fields removed
[DMSMVR-3518]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3518: Webform to create a form submission is unavailable for newly created forms.

- data/leisure_events.json
Ticket: https://simpleviewtools.atlassian.net/browse/DMSMVR-3532
A couple of the events had date rule sets that do not have required fields from the forms.
> DMSMVR-3532: Fix event data with missing end options

- data/forms.json
Ticket: [DMSMVR-3733](https://simpleviewtools.atlassian.net/browse/DMSMVR-3733)
Updates form data with new fields
[DMSMVR-3733]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3733: Partner Sign Up Form Settings

- data/account_media.json
- data/account_videos.json
Ticket: [DMSMVR-3652](https://simpleviewtools.atlassian.net/browse/DMSMVR-3652)
Adds vimeo videos to demo data.
[DMSMVR-3652]: https://simpleviewtools.atlassian.net/browse/DMSMVR-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-3652: Media: Video Form - Add Video Type Vimeo

- data/files.json
Ticket: [DMSMVR-2815](https://simpleviewtools.atlassian.net/browse/DMSMVR-2815)
Added height and width fields to image files with public URLs.
[DMSMVR-2815]: https://simpleviewtools.atlassian.net/browse/DMSMVR-2815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMSMVR-2815 - Show 'Image Size' (dimensions) on Images
